# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-19 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataUji',
            fields=[
                ('id_pengujian', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('total_dataset', models.IntegerField()),
                ('data_train', models.IntegerField()),
                ('data_test', models.IntegerField()),
                ('presisi', models.FloatField()),
                ('recall', models.FloatField()),
                ('akurasi', models.FloatField()),
            ],
            options={
                'db_table': 'pengujian',
            },
        ),
    ]
