# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-19 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id_dataset', models.AutoField(primary_key=True, serialize=False)),
                ('konten', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dataset',
            },
        ),
    ]
